services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - HTTP_HOST=${HTTP_HOST:-0.0.0.0}
      - HTTP_PORT=${HTTP_PORT:-8000}
    image: user_service:latest
    command: /app/drogon_user_service --action=run-server
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
