#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$project_dir"

if [[ ! -f .env ]]; then
  echo "Missing .env. Run a local setup script or create .env first." >&2
  exit 1
fi

# .env is a local, trusted configuration file generated by this repository.
set -a
# shellcheck disable=SC1091
source ./.env
set +a

: "${DB_HOST:?DB_HOST is required}"
: "${DB_NAME:?DB_NAME is required}"
: "${DB_USER:?DB_USER is required}"
export PGPASSWORD="${DB_PASSWORD:-}"

psql_args=(-h "$DB_HOST" -p "${DB_PORT:-5432}" -U "$DB_USER" -d "$DB_NAME")
psql "${psql_args[@]}" --set ON_ERROR_STOP=1 <<'SQL'
CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
SQL

shopt -s nullglob
migrations=(db/migrations/*.sql)
if [[ ${#migrations[@]} -eq 0 ]]; then
  echo "No migrations found."
  exit 0
fi

for migration in "${migrations[@]}"; do
  version="$(basename "$migration" .sql)"
  already_applied="$(psql "${psql_args[@]}" --tuples-only --no-align \
    --set ON_ERROR_STOP=1 \
    --command "SELECT 1 FROM public.schema_migrations WHERE version = '$version'")"
  if [[ "$already_applied" == "1" ]]; then
    echo "Skipping $version"
    continue
  fi

  echo "Applying $version"
  psql "${psql_args[@]}" --set ON_ERROR_STOP=1 --single-transaction \
    --file "$migration" \
    --command "INSERT INTO public.schema_migrations(version) VALUES ('$version')"
done
